version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/app-1.0-SNAPSHOT.jar
